# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(332, 358)
        Form.setStyleSheet("QPushButton, QLineEdit{\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"    border-radius:10px;\n"
"}\n"
"QLineEdit{\n"
"    \n"
"    font: 63 italic 10pt \"Segoe UI\";\n"
"    color:white;\n"
"    border-color:white;\n"
"\n"
"\n"
"}\n"
"QWidget{\n"
"    background-color: rgba(45, 45, 45);\n"
"}")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 331, 361))
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.title = QtWidgets.QLabel(self.login_page)
        self.title.setGeometry(QtCore.QRect(0, 10, 331, 31))
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 14pt \"Segoe UI Black\";")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.credits = QtWidgets.QLabel(self.login_page)
        self.credits.setGeometry(QtCore.QRect(10, 330, 161, 16))
        self.credits.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Lemon/Milk\";")
        self.credits.setObjectName("credits")
        self.email_input = QtWidgets.QLineEdit(self.login_page)
        self.email_input.setGeometry(QtCore.QRect(20, 100, 291, 31))
        self.email_input.setStyleSheet("")
        self.email_input.setAlignment(QtCore.Qt.AlignCenter)
        self.email_input.setObjectName("email_input")
        self.email_label = QtWidgets.QLabel(self.login_page)
        self.email_label.setGeometry(QtCore.QRect(0, 60, 331, 21))
        self.email_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 14pt \"Open Sans Light\";")
        self.email_label.setAlignment(QtCore.Qt.AlignCenter)
        self.email_label.setObjectName("email_label")
        self.password_input = QtWidgets.QLineEdit(self.login_page)
        self.password_input.setGeometry(QtCore.QRect(20, 190, 291, 31))
        self.password_input.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.password_input.setStyleSheet("")
        self.password_input.setAlignment(QtCore.Qt.AlignCenter)
        self.password_input.setObjectName("password_input")
        self.password_label = QtWidgets.QLabel(self.login_page)
        self.password_label.setGeometry(QtCore.QRect(0, 150, 331, 21))
        self.password_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 14pt \"Open Sans Light\";")
        self.password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.signup_button = QtWidgets.QPushButton(self.login_page)
        self.signup_button.setGeometry(QtCore.QRect(90, 280, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(7)
        self.signup_button.setFont(font)
        self.signup_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup_button.setStyleSheet("border-style:none;\n"
"font: 63 italic 9pt \"Open Sans\";\n"
"color: rgb(0, 85, 255);")
        self.signup_button.setObjectName("signup_button")
        self.login_button = QtWidgets.QPushButton(self.login_page)
        self.login_button.setGeometry(QtCore.QRect(80, 240, 181, 31))
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI Emoji\";\n"
"border-color:green;")
        self.login_button.setObjectName("login_button")
        self.stackedWidget.addWidget(self.login_page)
        self.signup_page = QtWidgets.QWidget()
        self.signup_page.setObjectName("signup_page")
        self.title_2 = QtWidgets.QLabel(self.signup_page)
        self.title_2.setGeometry(QtCore.QRect(0, 10, 331, 31))
        self.title_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 14pt \"Segoe UI Black\";")
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.email_label_2 = QtWidgets.QLabel(self.signup_page)
        self.email_label_2.setGeometry(QtCore.QRect(0, 60, 331, 21))
        self.email_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 14pt \"Open Sans Light\";")
        self.email_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.email_label_2.setObjectName("email_label_2")
        self.signup_email_input = QtWidgets.QLineEdit(self.signup_page)
        self.signup_email_input.setGeometry(QtCore.QRect(20, 100, 291, 31))
        self.signup_email_input.setStyleSheet("")
        self.signup_email_input.setAlignment(QtCore.Qt.AlignCenter)
        self.signup_email_input.setObjectName("signup_email_input")
        self.password_label_2 = QtWidgets.QLabel(self.signup_page)
        self.password_label_2.setGeometry(QtCore.QRect(0, 150, 331, 21))
        self.password_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 14pt \"Open Sans Light\";")
        self.password_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label_2.setObjectName("password_label_2")
        self.signup_password_input = QtWidgets.QLineEdit(self.signup_page)
        self.signup_password_input.setGeometry(QtCore.QRect(20, 190, 291, 31))
        self.signup_password_input.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.signup_password_input.setStyleSheet("")
        self.signup_password_input.setAlignment(QtCore.Qt.AlignCenter)
        self.signup_password_input.setObjectName("signup_password_input")
        self.register_button = QtWidgets.QPushButton(self.signup_page)
        self.register_button.setGeometry(QtCore.QRect(75, 240, 181, 31))
        self.register_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI Emoji\";\n"
"border-color:green;")
        self.register_button.setObjectName("register_button")
        self.already_a_user_button = QtWidgets.QPushButton(self.signup_page)
        self.already_a_user_button.setGeometry(QtCore.QRect(85, 280, 151, 23))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(7)
        self.already_a_user_button.setFont(font)
        self.already_a_user_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.already_a_user_button.setStyleSheet("border-style:none;\n"
"font: 63 italic 9pt \"Open Sans\";\n"
"color: rgb(0, 85, 255);")
        self.already_a_user_button.setObjectName("already_a_user_button")
        self.credits_2 = QtWidgets.QLabel(self.signup_page)
        self.credits_2.setGeometry(QtCore.QRect(10, 330, 161, 16))
        self.credits_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Lemon/Milk\";")
        self.credits_2.setObjectName("credits_2")
        self.stackedWidget.addWidget(self.signup_page)
        self.auth_page = QtWidgets.QWidget()
        self.auth_page.setObjectName("auth_page")
        self.title_3 = QtWidgets.QLabel(self.auth_page)
        self.title_3.setGeometry(QtCore.QRect(0, 10, 331, 31))
        self.title_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 14pt \"Segoe UI Black\";")
        self.title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title_3.setObjectName("title_3")
        self.label = QtWidgets.QLabel(self.auth_page)
        self.label.setGeometry(QtCore.QRect(0, 60, 331, 41))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.auth_code_input = QtWidgets.QLineEdit(self.auth_page)
        self.auth_code_input.setGeometry(QtCore.QRect(80, 130, 161, 31))
        self.auth_code_input.setAlignment(QtCore.Qt.AlignCenter)
        self.auth_code_input.setObjectName("auth_code_input")
        self.submit_auth_button = QtWidgets.QPushButton(self.auth_page)
        self.submit_auth_button.setGeometry(QtCore.QRect(60, 190, 211, 31))
        self.submit_auth_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_auth_button.setStyleSheet("color: rgb(0, 255, 0);\n"
"font: 11pt \"Segoe UI Emoji\";\n"
"border-color:black;")
        self.submit_auth_button.setObjectName("submit_auth_button")
        self.credits_3 = QtWidgets.QLabel(self.auth_page)
        self.credits_3.setGeometry(QtCore.QRect(10, 330, 161, 16))
        self.credits_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"Lemon/Milk\";")
        self.credits_3.setObjectName("credits_3")
        self.stackedWidget.addWidget(self.auth_page)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "Password Ch3cker "))
        self.credits.setText(_translate("Form", "CREATED BY MOE ALSHOUBAKI"))
        self.email_label.setText(_translate("Form", "Email"))
        self.password_label.setText(_translate("Form", "Password"))
        self.signup_button.setText(_translate("Form", "New here? Register here"))
        self.login_button.setText(_translate("Form", "Login"))
        self.title_2.setText(_translate("Form", "Sign up"))
        self.email_label_2.setText(_translate("Form", "Email"))
        self.password_label_2.setText(_translate("Form", "Password"))
        self.register_button.setText(_translate("Form", "Register"))
        self.already_a_user_button.setText(_translate("Form", "Already a user? Click here"))
        self.credits_2.setText(_translate("Form", "CREATED BY MOE ALSHOUBAKI"))
        self.title_3.setText(_translate("Form", "Verification"))
        self.label.setText(_translate("Form", "<html><head/><body><p>We\'ve sent a verification code to your <span style=\" font-weight:600;\">email</span>.</p><p>Enter the code below to proceed.</p></body></html>"))
        self.submit_auth_button.setText(_translate("Form", "Submit"))
        self.credits_3.setText(_translate("Form", "CREATED BY MOE ALSHOUBAKI"))
