# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2 import QtCore, QtGui, QtWidgets
from password_checker import alert_rc
from password_checker.icons import cilcheckalt
from password_checker.icons import go_back_button

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(903, 497)
        Form.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.credits = QtWidgets.QLabel(Form)
        self.credits.setGeometry(QtCore.QRect(6, -8, 901, 51))
        self.credits.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 24pt \"Segoe UI Black\";")
        self.credits.setAlignment(QtCore.Qt.AlignCenter)
        self.credits.setObjectName("credits")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 50, 881, 401))
        self.stackedWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(34, 34, 34);\n"
"    border-radius:10px;\n"
"\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 66);\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"    border:none;\n"
"    background: rgb(55, 63, 77);\n"
"    height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollbar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"    background:none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.warning_page = QtWidgets.QWidget()
        self.warning_page.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.warning_page.setStyleSheet("QPushButton{\n"
"    border-style:outset;\n"
"    border-width:2px;\n"
"    border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 87 12pt \"Segoe UI Black\";\n"
"}\n"
"QWidget{\n"
"    background-color: rgb(34, 34, 34);\n"
"}\n"
"\n"
"")
        self.warning_page.setObjectName("warning_page")
        self.warning_label = QtWidgets.QLabel(self.warning_page)
        self.warning_label.setGeometry(QtCore.QRect(0, 30, 881, 41))
        self.warning_label.setStyleSheet("color: rgb(170, 85, 255);\n"
"font: 25 20pt \"Segoe UI Bold\";\n"
"")
        self.warning_label.setAlignment(QtCore.Qt.AlignCenter)
        self.warning_label.setObjectName("warning_label")
        self.label_3 = QtWidgets.QLabel(self.warning_page)
        self.label_3.setGeometry(QtCore.QRect(310, 30, 61, 41))
        self.label_3.setStyleSheet("image: url(:/alert/alert.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.warning_page)
        self.label_4.setGeometry(QtCore.QRect(510, 30, 61, 41))
        self.label_4.setStyleSheet("image: url(:/alert/alert.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.warning_page)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 871, 291))
        self.label_5.setStyleSheet("font: 25 13pt \"Open Sans\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.accept_button = QtWidgets.QPushButton(self.warning_page)
        self.accept_button.setGeometry(QtCore.QRect(230, 300, 121, 41))
        self.accept_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.accept_button.setStyleSheet("border-color:rgb(0, 214, 0);")
        self.accept_button.setObjectName("accept_button")
        self.decline_button = QtWidgets.QPushButton(self.warning_page)
        self.decline_button.setGeometry(QtCore.QRect(550, 300, 121, 41))
        self.decline_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.decline_button.setStyleSheet("border-color:red;")
        self.decline_button.setObjectName("decline_button")
        self.stackedWidget.addWidget(self.warning_page)
        self.fetching_page = QtWidgets.QWidget()
        self.fetching_page.setObjectName("fetching_page")
        self.label = QtWidgets.QLabel(self.fetching_page)
        self.label.setGeometry(QtCore.QRect(10, 3, 861, 391))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 63 italic 22pt \"Open Sans\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.fetching_page)
        self.scrape_page = QtWidgets.QWidget()
        self.scrape_page.setStyleSheet("Line{\n"
"    border: 0.5px solid white;\n"
"    border-style: inset;\n"
"}\n"
"")
        self.scrape_page.setObjectName("scrape_page")
        self.label_6 = QtWidgets.QLabel(self.scrape_page)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 201, 21))
        self.label_6.setStyleSheet("font: 63 15pt \"Segoe UI Semibold\";\n"
"color: rgb(30, 97, 255);")
        self.label_6.setObjectName("label_6")
        self.google_chrome_label = QtWidgets.QLabel(self.scrape_page)
        self.google_chrome_label.setGeometry(QtCore.QRect(10, 80, 141, 21))
        self.google_chrome_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.google_chrome_label.setObjectName("google_chrome_label")
        self.chrome_pass_amount = QtWidgets.QLabel(self.scrape_page)
        self.chrome_pass_amount.setGeometry(QtCore.QRect(152, 82, 61, 21))
        self.chrome_pass_amount.setStyleSheet("color: rgb(65, 195, 0);\n"
"font: 25 11pt \"Lemon/Milk light\";")
        self.chrome_pass_amount.setObjectName("chrome_pass_amount")
        self.Firefox_label = QtWidgets.QLabel(self.scrape_page)
        self.Firefox_label.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.Firefox_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.Firefox_label.setObjectName("Firefox_label")
        self.firefox_pass_amount = QtWidgets.QLabel(self.scrape_page)
        self.firefox_pass_amount.setGeometry(QtCore.QRect(90, 112, 81, 21))
        self.firefox_pass_amount.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 25 11pt \"Lemon/Milk light\";")
        self.firefox_pass_amount.setObjectName("firefox_pass_amount")
        self.edge_label = QtWidgets.QLabel(self.scrape_page)
        self.edge_label.setGeometry(QtCore.QRect(10, 140, 141, 21))
        self.edge_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.edge_label.setObjectName("edge_label")
        self.edge_pass_amount = QtWidgets.QLabel(self.scrape_page)
        self.edge_pass_amount.setGeometry(QtCore.QRect(146, 142, 71, 21))
        self.edge_pass_amount.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 25 11pt \"Lemon/Milk light\";")
        self.edge_pass_amount.setObjectName("edge_pass_amount")
        self.start_button = QtWidgets.QPushButton(self.scrape_page)
        self.start_button.setGeometry(QtCore.QRect(305, 80, 221, 51))
        self.start_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_button.setStyleSheet("color: rgb(85, 255, 0);\n"
"font: 87 22pt \"Segoe UI Black\";\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:10px;\n"
"border-color:white;")
        self.start_button.setObjectName("start_button")
        self.label_13 = QtWidgets.QLabel(self.scrape_page)
        self.label_13.setGeometry(QtCore.QRect(620, 40, 201, 21))
        self.label_13.setStyleSheet("font: 63 15pt \"Segoe UI Semibold\";\n"
"color: rgb(30, 97, 255);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.scrape_page)
        self.label_14.setGeometry(QtCore.QRect(620, 80, 121, 21))
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.scrape_page)
        self.label_15.setGeometry(QtCore.QRect(620, 110, 171, 21))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.label_15.setObjectName("label_15")
        self.amount_of_pswds_checked = QtWidgets.QLabel(self.scrape_page)
        self.amount_of_pswds_checked.setGeometry(QtCore.QRect(317, 170, 191, 21))
        self.amount_of_pswds_checked.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";")
        self.amount_of_pswds_checked.setAlignment(QtCore.Qt.AlignCenter)
        self.amount_of_pswds_checked.setObjectName("amount_of_pswds_checked")
        self.label_17 = QtWidgets.QLabel(self.scrape_page)
        self.label_17.setGeometry(QtCore.QRect(620, 140, 151, 21))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.label_17.setObjectName("label_17")
        self.weak_pass_amount = QtWidgets.QLabel(self.scrape_page)
        self.weak_pass_amount.setGeometry(QtCore.QRect(742, 85, 120, 14))
        self.weak_pass_amount.setStyleSheet("color: rgb(255, 0, 0);")
        self.weak_pass_amount.setObjectName("weak_pass_amount")
        self.recurring_pass_amount = QtWidgets.QLabel(self.scrape_page)
        self.recurring_pass_amount.setGeometry(QtCore.QRect(780, 115, 120, 14))
        self.recurring_pass_amount.setStyleSheet("color: rgb(255, 0, 0);")
        self.recurring_pass_amount.setObjectName("recurring_pass_amount")
        self.leaked_pass_amount = QtWidgets.QLabel(self.scrape_page)
        self.leaked_pass_amount.setGeometry(QtCore.QRect(775, 145, 120, 14))
        self.leaked_pass_amount.setStyleSheet("color: rgb(255, 0, 0);")
        self.leaked_pass_amount.setObjectName("leaked_pass_amount")
        self.full_summary_button = QtWidgets.QPushButton(self.scrape_page)
        self.full_summary_button.setGeometry(QtCore.QRect(790, 170, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(3)
        self.full_summary_button.setFont(font)
        self.full_summary_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.full_summary_button.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 italic 10pt \"Segoe UI Light\";")
        self.full_summary_button.setObjectName("full_summary_button")
        self.console = QtWidgets.QTextEdit(self.scrape_page)
        self.console.setGeometry(QtCore.QRect(10, 230, 861, 151))
        self.console.setStyleSheet("QTextEdit {\n"
"    border-radius:10px;\n"
"    padding: 5px;\n"
"    font: 75 9pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-style:outset;\n"
"    border-width: 2px;\n"
"    border-color:rgb(75, 164, 255);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid;\n"
"    border-color: rgb(58,66,81);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    background: 3px solid;\n"
"    border-color: rgb(85, 255, 127);\n"
"    background-image: url(:/cil-check-alt/cil-check-alt.png);\n"
"}\n"
"")
        self.console.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.console.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        self.emails_checked_label = QtWidgets.QLabel(self.scrape_page)
        self.emails_checked_label.setGeometry(QtCore.QRect(320, 140, 191, 21))
        self.emails_checked_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";")
        self.emails_checked_label.setAlignment(QtCore.Qt.AlignCenter)
        self.emails_checked_label.setObjectName("emails_checked_label")
        self.stackedWidget.addWidget(self.scrape_page)
        self.summary_page = QtWidgets.QWidget()
        self.summary_page.setStyleSheet("QCheckBox {\n"
"    font: 63 12pt \"Open Sans SemiBold\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid; \n"
"        border-color: rgb(52, 59, 72);\n"
"        width: 15px;\n"
"        height: 15px;\n"
"    border-radius: 10px;    \n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid;\n"
"    border-color: rgb(58,66,81);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    background: 3px solid;\n"
"    border-color: rgb(85, 255, 127);\n"
"    \n"
"    image: url(:/cil-check-alt/cil-check-alt.png);\n"
"}")
        self.summary_page.setObjectName("summary_page")
        self.label_2 = QtWidgets.QLabel(self.summary_page)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 881, 41))
        font = QtGui.QFont()
        font.setFamily("Lemon/Milk")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(9)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Lemon/Milk\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.leaked_data_button = QtWidgets.QPushButton(self.summary_page)
        self.leaked_data_button.setGeometry(QtCore.QRect(80, 90, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.leaked_data_button.setFont(font)
        self.leaked_data_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.leaked_data_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 9pt \"Open Sans\";")
        self.leaked_data_button.setObjectName("leaked_data_button")
        self.reacurring_passwords_button = QtWidgets.QPushButton(self.summary_page)
        self.reacurring_passwords_button.setGeometry(QtCore.QRect(85, 120, 161, 23))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.reacurring_passwords_button.setFont(font)
        self.reacurring_passwords_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reacurring_passwords_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 9pt \"Open Sans\";")
        self.reacurring_passwords_button.setObjectName("reacurring_passwords_button")
        self.weak_passwords_button = QtWidgets.QPushButton(self.summary_page)
        self.weak_passwords_button.setGeometry(QtCore.QRect(160, 90, 101, 23))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        self.weak_passwords_button.setFont(font)
        self.weak_passwords_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.weak_passwords_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 9pt \"Open Sans\";")
        self.weak_passwords_button.setObjectName("weak_passwords_button")
        self.label_7 = QtWidgets.QLabel(self.summary_page)
        self.label_7.setGeometry(QtCore.QRect(6, 92, 71, 21))
        self.label_7.setStyleSheet("font: 63 15pt \"Segoe UI Semibold\";\n"
"color: rgb(30, 97, 255);")
        self.label_7.setObjectName("label_7")
        self.show_data_button = QtWidgets.QCheckBox(self.summary_page)
        self.show_data_button.setGeometry(QtCore.QRect(720, 130, 131, 21))
        self.show_data_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_data_button.setObjectName("show_data_button")
        self.QTable_Summaries = QtWidgets.QStackedWidget(self.summary_page)
        self.QTable_Summaries.setGeometry(QtCore.QRect(20, 160, 861, 221))
        self.QTable_Summaries.setObjectName("QTable_Summaries")
        self.leaked_data_page = QtWidgets.QWidget()
        self.leaked_data_page.setObjectName("leaked_data_page")
        self.summary_table = QtWidgets.QTableWidget(self.leaked_data_page)
        self.summary_table.setGeometry(QtCore.QRect(0, 0, 841, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summary_table.sizePolicy().hasHeightForWidth())
        self.summary_table.setSizePolicy(sizePolicy)
        self.summary_table.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QTableWidget::item {\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid;\n"
"    border-right: 1px solid;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QTableWidget:horizontalHeader{\n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px; \n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical {\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background:rgb(85, 255, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.summary_table.setLineWidth(1)
        self.summary_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.summary_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.summary_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.summary_table.setRowCount(0)
        self.summary_table.setObjectName("summary_table")
        self.summary_table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.summary_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.summary_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.summary_table.setHorizontalHeaderItem(2, item)
        self.summary_table.horizontalHeader().setDefaultSectionSize(269)
        self.summary_table.horizontalHeader().setMinimumSectionSize(39)
        self.summary_table.verticalHeader().setVisible(False)
        self.summary_table.verticalHeader().setDefaultSectionSize(30)
        self.summary_table.verticalHeader().setHighlightSections(True)
        self.summary_table.verticalHeader().setMinimumSectionSize(23)
        self.QTable_Summaries.addWidget(self.leaked_data_page)
        self.weak_passwords = QtWidgets.QWidget()
        self.weak_passwords.setObjectName("weak_passwords")
        self.weak_passwords_table = QtWidgets.QTableWidget(self.weak_passwords)
        self.weak_passwords_table.setGeometry(QtCore.QRect(0, 0, 841, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weak_passwords_table.sizePolicy().hasHeightForWidth())
        self.weak_passwords_table.setSizePolicy(sizePolicy)
        self.weak_passwords_table.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QTableWidget::item {\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid;\n"
"    border-right: 1px solid;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QTableWidget:horizontalHeader{\n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px; \n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical {\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    \n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.weak_passwords_table.setLineWidth(1)
        self.weak_passwords_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.weak_passwords_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.weak_passwords_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.weak_passwords_table.setRowCount(0)
        self.weak_passwords_table.setObjectName("weak_passwords_table")
        self.weak_passwords_table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.weak_passwords_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.weak_passwords_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.weak_passwords_table.setHorizontalHeaderItem(2, item)
        self.weak_passwords_table.horizontalHeader().setDefaultSectionSize(269)
        self.weak_passwords_table.horizontalHeader().setMinimumSectionSize(39)
        self.weak_passwords_table.verticalHeader().setVisible(False)
        self.weak_passwords_table.verticalHeader().setDefaultSectionSize(30)
        self.weak_passwords_table.verticalHeader().setHighlightSections(True)
        self.weak_passwords_table.verticalHeader().setMinimumSectionSize(23)
        self.QTable_Summaries.addWidget(self.weak_passwords)
        self.reaccuring_passwords_page = QtWidgets.QWidget()
        self.reaccuring_passwords_page.setObjectName("reaccuring_passwords_page")
        self.reacurring_passwords_table = QtWidgets.QTableWidget(self.reaccuring_passwords_page)
        self.reacurring_passwords_table.setGeometry(QtCore.QRect(0, 0, 841, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reacurring_passwords_table.sizePolicy().hasHeightForWidth())
        self.reacurring_passwords_table.setSizePolicy(sizePolicy)
        self.reacurring_passwords_table.setStyleSheet("QTableWidget {\n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QTableWidget::item {\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid;\n"
"    border-right: 1px solid;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QTableWidget:horizontalHeader{\n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px; \n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical {\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background:rgb(255, 0, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.reacurring_passwords_table.setLineWidth(1)
        self.reacurring_passwords_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.reacurring_passwords_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.reacurring_passwords_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.reacurring_passwords_table.setRowCount(0)
        self.reacurring_passwords_table.setObjectName("reacurring_passwords_table")
        self.reacurring_passwords_table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.reacurring_passwords_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.reacurring_passwords_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.reacurring_passwords_table.setHorizontalHeaderItem(2, item)
        self.reacurring_passwords_table.horizontalHeader().setDefaultSectionSize(269)
        self.reacurring_passwords_table.horizontalHeader().setMinimumSectionSize(39)
        self.reacurring_passwords_table.verticalHeader().setVisible(False)
        self.reacurring_passwords_table.verticalHeader().setDefaultSectionSize(30)
        self.reacurring_passwords_table.verticalHeader().setHighlightSections(True)
        self.reacurring_passwords_table.verticalHeader().setMinimumSectionSize(23)
        self.QTable_Summaries.addWidget(self.reaccuring_passwords_page)
        self.title_of_table = QtWidgets.QLabel(self.summary_page)
        self.title_of_table.setGeometry(QtCore.QRect(330, 129, 221, 21))
        self.title_of_table.setStyleSheet("font: 14pt \"HACKED\";\n"
"color: rgb(255, 255, 255);")
        self.title_of_table.setAlignment(QtCore.Qt.AlignCenter)
        self.title_of_table.setObjectName("title_of_table")
        self.go_back_from_summary = QtWidgets.QPushButton(self.summary_page)
        self.go_back_from_summary.setGeometry(QtCore.QRect(10, 10, 41, 31))
        self.go_back_from_summary.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_back_from_summary.setStyleSheet("image: url(:/go_back_button/go_back_button.png);")
        self.go_back_from_summary.setText("")
        self.go_back_from_summary.setObjectName("go_back_from_summary")
        self.stackedWidget.addWidget(self.summary_page)
        self.credit_c = QtWidgets.QLabel(Form)
        self.credit_c.setGeometry(QtCore.QRect(10, 460, 191, 31))
        self.credit_c.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Lemon/Milk\";")
        self.credit_c.setObjectName("credit_c")
        self.ysu_hackathon_tag = QtWidgets.QLabel(Form)
        self.ysu_hackathon_tag.setGeometry(QtCore.QRect(760, 460, 141, 16))
        self.ysu_hackathon_tag.setStyleSheet("color: rgb(185, 28, 57);\n"
"\n"
"font: 75 11pt \"Lemon/Milk\";")
        self.ysu_hackathon_tag.setObjectName("ysu_hackathon_tag")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.QTable_Summaries.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.credits.setText(_translate("Form", "Password Ch3cker"))
        self.warning_label.setText(_translate("Form", "WARNING"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p>This program will have to fetch the saved passwords to the current machine.</p><p>The program will <span style=\" font-weight:600;\">not</span> share your passwords in any way or form.</p><p>It will only collect the emails/password store to compare to online leaked databases.</p><p>By pressing &quot;Accept&quot; you understand and accept. </p></body></html>"))
        self.accept_button.setText(_translate("Form", "Accept"))
        self.decline_button.setText(_translate("Form", "Decline"))
        self.label.setText(_translate("Form", "Fetching Passwords..."))
        self.label_6.setText(_translate("Form", "Fetched Passwords:"))
        self.google_chrome_label.setText(_translate("Form", "⚪ Google Chrome:"))
        self.chrome_pass_amount.setText(_translate("Form", "0"))
        self.Firefox_label.setText(_translate("Form", "⚫ Firefox:"))
        self.firefox_pass_amount.setText(_translate("Form", "0"))
        self.edge_label.setText(_translate("Form", "⚫ Microsoft Edge:"))
        self.edge_pass_amount.setText(_translate("Form", "0"))
        self.start_button.setText(_translate("Form", "Start"))
        self.label_13.setText(_translate("Form", "Results:"))
        self.label_14.setText(_translate("Form", "Weak Passwords:"))
        self.label_15.setText(_translate("Form", "Re-curring Passwords:"))
        self.amount_of_pswds_checked.setText(_translate("Form", "0 / 0 Passwords Checked"))
        self.label_17.setText(_translate("Form", "Found Leaked Online:"))
        self.weak_pass_amount.setText(_translate("Form", "Waiting to start..."))
        self.recurring_pass_amount.setText(_translate("Form", "Waiting to start..."))
        self.leaked_pass_amount.setText(_translate("Form", "Waiting to start..."))
        self.full_summary_button.setText(_translate("Form", "Full Summary"))
        self.emails_checked_label.setText(_translate("Form", "0 / 0 Emails Checked"))
        self.label_2.setText(_translate("Form", "Summary"))
        self.leaked_data_button.setText(_translate("Form", "Leaked Data"))
        self.reacurring_passwords_button.setText(_translate("Form", "Re-accuring Passwords"))
        self.weak_passwords_button.setText(_translate("Form", "Weak Passwords"))
        self.label_7.setText(_translate("Form", "Filters:"))
        self.show_data_button.setText(_translate("Form", "Show Data"))
        item = self.summary_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Email"))
        item = self.summary_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Last Breach"))
        item = self.summary_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Amount"))
        item = self.weak_passwords_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Email/Username"))
        item = self.weak_passwords_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Site"))
        item = self.weak_passwords_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Password"))
        item = self.reacurring_passwords_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Email/Username"))
        item = self.reacurring_passwords_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Site"))
        item = self.reacurring_passwords_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Password"))
        self.title_of_table.setText(_translate("Form", "Leaked Data"))
        self.credit_c.setText(_translate("Form", "Created by Moe Alshoubaki"))
        self.ysu_hackathon_tag.setText(_translate("Form", "YSU 2021 Hackathon"))
